### ISSUE TITLE
[Request] SMPL parameters for LargeCrowd dataset

### ISSUE THREAD

**Issue by Wei-Chen-hub** [1020244018/Crowd3D#1]
Hi Crowd3d Team,

Thanks for providing an interesting dataset.

I'm considering to include LargeCrowd in human preception model training, but seems that SMPL parameters are not released. Would you consider to release the SMPL parameters?

**Comment by 1020244018** [comment]
Hi, Wei-Chen-hub,
The LargeCrowd dataset itself does not contain annotations of SMPL parameters.
We recommend you try some pseudo 3D data construction methods, which may help you, such as [EFT](https://github.com/facebookresearch/eft).
